# Generated by Django 2.2.17 on 2023-02-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230221_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=1),
        ),
    ]
