# Generated by Django 2.2.17 on 2023-02-27 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230221_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=100),
        ),
        migrations.AlterField(
            model_name='activation',
            name='trial_valid_until',
            field=models.DateField(default=datetime.date(2023, 3, 14)),
        ),
    ]
