# Generated by Django 2.2.17 on 2023-02-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230227_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(max_length=100),
        ),
    ]
