# Generated by Django 2.2.17 on 2023-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
