# Generated by Django 2.2.17 on 2023-04-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201128_1441'),
        ('accounts', '0009_auto_20230227_1918'),
    ]

    operations = [
    ]
