# Generated by Django 2.2.17 on 2023-06-02 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230601_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='trial_valid_until',
            field=models.DateField(default=datetime.date(2023, 6, 18)),
        ),
    ]
