# Generated by Django 2.2.17 on 2023-06-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230529_1046'),
        ('accounts', '0013_auto_20230603_0020'),
    ]

    operations = [
    ]
