# Generated by Django 2.2.17 on 2023-02-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
